name: Test npm package

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version to test'
        required: true

jobs:
  test_npm_package:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-latest, windows-2019, macos-10.15 ]
        node-version: [ 12.x, 14.x, 16.x, 17.x ]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up the unit tests
      run: |
        curl https://codeload.github.com/mmomtchev/rlayers/zip/refs/tags/v${{ github.event.inputs.version }} --output repo.zip
        unzip repo.zip
        mv rlayers-${{ github.event.inputs.version }}/package.json .
        mv rlayers-${{ github.event.inputs.version }}/tsconfig.json .
        mv rlayers-${{ github.event.inputs.version }}/jest*config.js .
        mv rlayers-${{ github.event.inputs.version }}/examples .
        mv rlayers-${{ github.event.inputs.version }}/test .
        npm install
    - name: Install from npm
      run:  npm install --force rlayers@${{ github.event.inputs.version }}
    - name: Run the unit tests
      run: npx jest -c jest.standalone.config.js

